version: '3'

services:
  auth-service:
	build: ./auth-service
	ports:
  	- "5000:5000"
	networks:
  	- app-network

  users-service:
	build: ./users-service
	ports:
  	- "5001:5001"
	networks:
  	- app-network
	depends_on:
  	- postgres

  orders-service:
	build: ./orders-service
	ports:
  	- "5004:5004"
	networks:
  	- app-network
	depends_on:
  	- postgres
  	- products-service

  products-service:
	build: ./products-service
	ports:
  	- "5002:5002"
	networks:
  	- app-network
	depends_on:
  	- mongo

  postgres:
	image: postgres:13
	environment:
  	POSTGRES_USER: user
  	POSTGRES_PASSWORD: password
  	POSTGRES_DB: users_db
	volumes:
  	- postgres-data:/var/lib/postgresql/data
	networks:
  	- app-network

  mongo:
	image: mongo:4.4
	volumes:
  	- mongo-data:/data/db
	networks:
  	- app-network

volumes:
  postgres-data:
  mongo-data:

networks:
  app-network:

